#+title: Analysis

* TODO Introduzione

* Tools and preliminary steps
# Prima di introdurre le procedure applicate per raccogliere insights riguardo MIMIC-III, per permettere di riprodurre le analisi effettuate in modo corretto è utile elencare gli strumenti utilizzati e gli step preparatori effettuati.
Before introducing the procedures applied to gather insights regarding MIMIC-III, to enable the analyses performed to be reproduced properly, it is useful to list the tools used and the preparatory steps taken.

# Come spiegato nella sezione [], per ottenere accesso a MIMIC-III è stato necessario completare un corso obbligatorio di formazione sulla protezione di dati con rilevanza medica di terzi.
As explained in section [], in order to obtain access to MIMIC-III, it was necessary to complete a mandatory training course on the protection of data with third-party medical relevance.
# Una volta ottenuto accesso al dataset, abbiamo considerato le varie opportunità a nostra disposizione per effettuare query sui dati messi a disposizione; Tra le varie opzioni abbiamo scelto il self hosting, utilizzando PostgreSQL come database system in quanto più familiare.
Once we obtained access to the dataset, we considered the various opportunities available to us for querying the data made available; Of the various options, we chose self-hosting, using PostgreSQL as the database system since it was more familiar.
# Per evitare conflitti con altri applicativi di sistema e rendere il programma predicibile, è stato scelto di utilizzare docker per contain the dbms.
To avoid conflicts with other system applications and to make the program predictable, we chose to use docker to contain the database.

# Il tool scelto per lo sviluppo delle analisi è stato JupyterLab, un web-based development enviroment, scegliendo python come linguaggio di programmazione.
The tool chosen for analysis development was JupyterLab, a web-based development enviroment, choosing python as the programming language.
# La libreria utilizzata per l'interazione con PostgreSQL nell'ambiente di sviluppo JupyterLab è Psycopg2, a PostgresQL adapter for the python language.
To interact with the PostgreSQL database in the JupyterLab development environment we leveraged Psycopg2, a PostgresQL adapter for the python language.

** Pre-processing of the waveforms
# Per poter effettuare un'analisi delle waveform con l'obiettivo di simularne la distribuzione temporale, è risultato necessario elaborarle per estrarre le informazioni necessarie riguardanti le tempistiche.
In order to carry out an analysis of the waveforms with the aim of simulating their temporal distribution, it was necessary to process them to extract the necessary information concerning timing.

# Come presentato nella sezione [], each recording is split into multiple files, also called /segments/. Each segment is associated to its own header file.
As presented in section [], each record is divided into several files, also called /segments/. Each segment is associated with its own header file.

In the matched waveform subset, each recording is associated to a /master header file/, which provides the subject_id of the patients as well as the surrogate time and date of the recording and the segments that comprise such recording;
Such master header file (of which an example is shown in figure []) was used to gather most of the necessary informations about the waveform recordings.

Moreover, a /layout file/ (of which a sample is shown in figure []) is associated to each recording and shows which signals are registered with each sample during the duration of the recording.

The informations of interest in the header file are:
- The subject_id of the patient of which the recording was performed
- The sampling frequency of the recording (amount of samples transmitted per second), highlighted in figure [] in _
- The total amount of samples transmitted during the recording, highlighted in figure [] in _
- The timestamp of the recording, highlighted in figure [] in _
- The layout file associated with the recording.
- The pauses between transmissions, labeled by a \~ at the start of the line, and their duration (in terms of 'untrasmitted samples', or sample frequency units), highlighted in _
- For each segment, the amount of samples covered by it, highlighted in _

To facilitate the analysis, we gathered all these informations into a single table, which was then stored in the same database system containing mimic.
To reduce the amount of tuples, subsequent transmissions in the same recording were grouped together, as shown in figure [], and assigned to the signals derived by its layout file.

* Analysis of the behavior
** Why?
# Volendo modellare e riprodurre il flusso di dati tra il paziente e il sistema ospedaliero di cui mimic ci fornisce uno squarcio, è utilie, come prima cosa, cercare di individuare il pattern di interazione tra utenti e ospedale.

Since we wanted to model and reproduce the stream of information between the patient and the hospital system of which MIMIC gives us a glimpse, it is useful, as a first step, to try and understand the behavior of the users registered in the hospital system.

** Default behavior :traduzione:
As introduced in section [], MIMIC-III focuses on the data exchange between the patients who stayed in _critical care units_ of the Beth Israel Deaconess Medical Center and the data system of the hospital.
# %#TODO: sez in cui introduco mimic.

# Oltre a contenere le informazioni sulle permanenze in ICU dei pazienti (quali ad esempio data e ora di inizio e fine della icy stay) ha anche informazioni riguardati la loro intera permanenza ospedaliera fuori dai reparti di terapia intensiva.

Other than informations about the ICU stays of the patients, like date and time of start and finish of the ICU stay, MIMIC also contains informations about their entire hospital stay, covering also their time outside the intensive care units.

# Alcune tipologie di eventi sono collegate a (e avvengono durante) una permanenza in ICU, mentre altre sono invece associate all'intera permanenza ospedaliera.
# Per questo motivo, è importante definire i periodi in cui ciascuna di queste tipologie di eventi viene generata.

Some kinds of events are associated to (and happen during) an ICU stay, while others are associated to the entire hospital stay.

# Utilizzando i termini di MIMIC, diremo che il paziente è associato a una Admission dal momento in cui viene generato l'evento che segnala l'inizio della permanenza ospedaliera a quando viene segnata la fine della permanenza, mentre diremo che il paziente è associato a una ICU stay quando viene generato l'evento che segnala l'inizio della permanenza in ICU.
# TODO: capitolo MIMIC

Using some MIMIC terminology, we will say an event is "associated to an admission (or an hospital stay)" when the table it is registered in has the "hadm_id" attribute, that is to say that is was registered during the time when the hospital stay took place, while we will say that the event is "associated to an icustay" when its table possesses the attribute "icustay_id", that is to say it was registered during the time when the patient was in an ICU.
As one can guess, every event is associated to an hadm_id, since all registered events happened during an hospital stay, but not every category of events have an `icustay_id` associated.
# For additional information about the structure of MIMIC, please refer to [].

# %#TODO: capitolo mimic

# Una prima approssimazione del comportamento dei pazienti può essere la seguente:

# - Dopo l'inizio della permanenza ospedaliera, c'é un periodo di tempo prima dell'inizio della permanenza in ICU del paziente in cui il paziente è associato a un'admission ma non a una ICUstay.
# - Il paziente viene quindi ammesso in una ICU, dove comincia la sua ICU stay. Durante questo periodo, sono generati gli eventi associati alla ICU stay.
# - Il paziente esce dall'ICU
# - Dopo un periodo di tempo fuori dall'ICU, si conclude la sua admission.

# In tutti questi periodi di tempo, il paziente ha continuato a generare eventi legati alla sua admission.

# Le interazioni appena descritte sono formalizzate nel seguente UML activity diagram (gli elementi formali degli activity diagram sono descritti in link )

Based on this information, we can make a first approximation of the behavior of the patients inside the system:

- After the hospital stay has started, there's a time period before the start of the ICU stay of the patient in which she is associated to an hospital stay but not to an ICU stay.
- The patient then gets admitted into an intensive care unit, where her ICU stay starts. During the period inside the ICU, the events associated to the ICU stay are generated.
- The patient then exits the intensive care unit.
- After a period of time outside the ICU, her admission terminates.

During this whole time, the patient continues to generate events associated to her hospital stay.

The behavior described above can be formalized in the following UML activity diagram (the specification for UML activity diagrams can be found at []).

Since the focus of this work is on the interactions between the patient and the hospital system, the internal behavior of the hospital data system was vastly simplified.

# %#TODO: insert link to UML activity diagram sprcification

# %#TODO: UML activity diagram base

** Refinements on the behavioral model
# Il modello appena visto può essere migliorato facendo alcune considerazioni riguardanti MIMIC e confrontandole con i dati contenuti in esso.
The model just seen can be improved by making some hypotheses regarding MIMIC and validating them by looking at the data in it.

*** Multiple hospitalizations and multiple ICU stays

# Una delle prime considerazioni fatte ha introdotto la possibilità che lo stesso paziente avesse molteplici admissions e, all'interno della stessa permanenza ospedaliera, molteplici ICU stays.
# Le analisi fatte su MIMIC a riguardo hanno dato supporto a queste ipotesi, come mostrano i grafici riportati sotto:

One of the first considerations made introduced the possibility for the same patient to have multiple hospital stays and, during the same hospital stay, multiple ICU stays.
The analyzes made on MIMIC-III on this regard were made supported the hypotesis, as shown in the following figures.
# %#TODO: grafico admissions_amount.png
# %#TODO: grafico icustays_amount.png

# Come possiamo vedere, nonostante la maggioranza dei pazienti abbia una sola permanenza ospedaliera registrata e una singola permanenza in ICU, una porzione non trascurabile hanno molteplici admissions associate o molteplici icu stays associate alla stessa permanenza ospedaliera.

As we can see, even though the majority of the patients is associated to a single hospital stay and most hospital stays are associated to a single ICU stay, a non-negligible portion of patients has multiple admissions associated or multiple ICU stays associated to the same hospital stay.

# Visti questi risultati, è utile modificare il nostro modello delle interazioni per tenere in considerazione i pazienti sopra citati.
# L'activity diagram mostrato di seguito mostra il nuovo modello, considerando la possibilità che l'admission si ripeta o che ci sia un ulteriore permanenza in ICU oltre la prima.

Given these results, it is useful to update our patient behavior model to consider the patients mentioned above.
The activity diagram shown below shows the new model, that consdiers the possibility for an hospital stay to repeat and for another ICU stay other than the first to happen.

# %#TODO: activity diagram 2

# Come si può notare, tra permanenze ICU successive viene considerato un intervallo di tempo, denominato nel diagramma "wait time between icu stays".
# Questo periodo di tempo poteva non essere considerato separatamente dall'azione "wait after the ICU stay", ma abbiamo deciso di considerarli separamente già a questo stadio nell'eventualità che avessero una distribuzione differente.

As you can see, between successive ICU stays a time interval is considered, labeled in the diagram as "wait time between ICU stays".
This time period could be considered in conjunction with the period after the ICU stay shown in the previous version of the model, but we decided to consider them separately in the event that they have a different time distribution.

A similar time period is considered between successive hospital stays and labeled in the diagram as "wait time between hospital stays".
During this time period, the patient is not considered in the hospital premise and, as such, does not generate any sort of data to be stored in the hospital data system.

*** HOLD ICU stays that start immediately :traduzione:
Non le abbiamo considerate alla fine, ma possiamo mostrare che alcune partono dopo pochissimo tempo.

Mentre proseguivamo le nostre analisi su mimic, abbiamo avuto modo di notare che alcune permanenze ospedaliere cominciano immediatamente con una permanenza in ICU.

Abbiamo cercato quindi di analizzare le permanenze ospedaliere per capire se questo comportamento particolare fosse frutto di una caratteristica dell'intero dataset o se si trattasse di semplici outliers da non considerare.

Per questo motivo abbiamo cercato di raccogliere le permanenze in ICU che cominciassero a un breve .



*** Hospitalizations that end immediately after discharge from ICU
# Analizzando MIMIC alla ricerca di comportamenti fuori dallo standard abbiamo notato che un numero importante di permanenze ICU finisce dopo la permanenza ospedaliera a cui sono collegati (12762 permanenze in ICU su 61532).
# Come possiamo notare nel grafico sotto, che rappresenta la cumulative density function delle icustays "anomale", la maggior parte di esse ha al più un giorno di distanza dalla fine della admission ad essa collegata, con oltre il 75% al di sotto della soglia delle 3 ore.

During the analysis of MIMIC-III, looking for outstanding behaviors, we noticed that an important number of ICU stays (12762 of 61532) finish after the hospital stay to which they are associated (through the `icustays` table).
# %#TODO: mimic
As we can notice in the figure below, which represents the comulative density function of the abnormal icustays, the majority of them has at most one day of time distance after the end of the associated hospitalization, with over 75% below three hours.

# %#TODO: image: icustays-end-before-admissions_cdf

# Non avendo trovato informazioni a riguardo nella documentazione di MIMIC-III, per evitare che venissero perse o considerate scorrettamente successivamente, abbiamo deciso di considerarle come la fine reale delle permanenze ospedaliere.

Since we were not able to find informations about them in MIMIC-III's documentation, to prevent them from being lost or incorrectly considered later on, we decided to include them as the real finish time of the associated hospital stays.

# In accordo con questa considerazione, visto l'alto numero di permanenze ospedaliere che terminano immediatamente dopo la permanenza in ICU, abbiamo ritenuto opportuno considerare questa opportunità separatamente, introducendola nel nostro modello.
In accordance with this consideration and given the high number of hospital stays that finish immediately after the last ICU stay, we deemed it appropriate to consider this possibility separately by explicitly introducing it in our model.

# L'activity diagram aggiornato è mostrato di seguito:

The updated activity diagram is shown in the following figure.

# %#TODO: activity diagram

*** HOLD Hospitalizations that don't have an ICU stay

# Nel cercare informazioni aggiuntive riguardanti MIMIC, abbiamo trovato un altro caso limite, anche se meno evidente dei precedenti: una piccola porzione delle permanenze ospedaliere (1190 su 58976, corrispondente al 2%) non è associata con alcuna permanenza icu nella tabella ICUSTAYS di MIMIC-III (vedi la sezione [] per riguardanti le tabelle di mimic).

While looking for additional informations in MIMIC, we found another limit case, less evident than the ones previously considered: A small portion of the hospital stays (1190 over 58976, 2%) is not associated to any ICU stay in the ICUSTAYS table of MIMIC-III (see section [] for a presentation of the tables that comprise MIMIC-III).
# %#TODO: mimic

Although they do not represent a big portion of the cases considered (but still a significant one), due to their outstanding behavior we deemed useful to consider these admissions separately in our model, of which you can see the updated version below.

# %#TODO: diagramma noicu

# Alla fine del percorso di sviluppo del modello (quasi per caso) ci siamo resi conto del fatto che questa caratteristica fuori dalla norma per un dataset specializzato sulle permanenze in ICU è effettivamente un caso particolare: Queste permanenze ospedaliere erano collegate a degli eventi a loro volta associati a una permanenza in ICU, ma tale permanenza in ICU, nella tabella ICUSTAYS, era associata a una permanenza ospedaliera differente (anche se dello stesso paziente);
# Questa casistica non è sottolineata nella documentazione di MIMIC e mette in dubbio il fatto che durante alcune permanenze ospedaliere possano non avvenire icustays.

During the final stages of the development process for the model, we realized that this outstanding characteristic was indeed a peculiar case: the hospital stays described above are connected with some events, which in turn are associated to some icu stays, but these icu stays are associated to a different hospital stay (from the same patient) in the ICUSTAYS table;
This possibility is not described in MIMIC's documentation, and jeopardizes the correctness of the updated model.

# Essendo uno dei principali obiettivi del nostro modello la riusabilità (come sottolineato nella sezione []), abbiamo deciso di mantenere questa casistica in quanto, considerando un caso più generico, possiamo comunque assumere che durante alcune permanenze ospedaliere i pazienti non permangano in una ICU.

Since one of the main objective of our model is reusability though (as explained in section []), we decided to keep the modifications applied. After all, if we considered a more general case that did not cover only ICU patients, we could safely assume that some hospital stays would not result in an ICU stay.
# %#TODO: sezione design decisions

The activity updated activity diagram is shown in the figure below.

# %#TODO: activity diagram

*** Conclusion
In the model whose development was shown in this section we identified a total of 6 time intervals:
- The time in ICU, in which the events associated with the ICU are created.
- The time waiting before an admission and the first ICU stay
- The time between two consecutive ICU stays.
- The time between the end of the last ICU stay and the end of the entire hospital stay.
- The time between the end of an hospital stay and the beginning of the next one.
- The total time in the hospital, which shall be considered as the sum of the times listed above.

# The next step in our analysis is to find the distributions that correctly fit each of these time intervals (except the last one, which can be derived from the others).
# Il prossimo passo verso la creazione di un modello in grado di generare delle tracce di eventi comparabili a quelle descritte nel MIMIC-III dataset sarebbe to find the distributions that

The next step towards the creation of a model capable of generating event traces comparable to the ones present in the MIMIC-III dataset would be to find the distributions that correctly fit each of these time intervals (except the last one, which can be derived from the others)

Tuttavia, prima di introdurre quella sezione del lavoro è utilile parlare della classificazione che abbiamo deciso di applicare nel nostro modello e dei motivi che ci hanno portato a tale scelta.

However, before we introduce that part of the work, it's useful to present the classification that we have decided to apply in our model and the reasons that led us to those choices.

** Classification :traduzione:

# %#WHY
# Prima di concentrarci sulle distribuzioni che possono essere fit per modellare le interazioni identificate nella precedente sezione, abbiamo discusso la possibilità di effettuare una categorizzazione sui dati che avevamo a disposizione.

Before focusing on the distributions that can be fit to model the behaviors identified in the previous section, we discussed the possibility of categorizing the behaviors and events we had available.

# Dovendo scegliere delle distribuzioni che seguissero l'andamento di una grande mole di dati, abbiamo reputato utile introdurre questa possibilità.
# La decisione di dividere i dati in categorie è stata presa per fare in modo che le interazioni trovate e le distribuzioni scelte potessero essere meglio adattate l'un l'altra.
# Dividendo il dataset in categorie, possiamo infatti sperare di raggruppare le interazioni e gli eventi con distribuzioni simili così da rendere il modello più fedele alla realtà.
# Anche nel caso in cui le classi scelte non ottengano l'effetto desiderato, introdurre questa possibilità nel nostro modello ne giova la versatilità e apre potenzialmente le porte a classificazioni più sofisticate e più performanti.

The decision to divide the data into categories was made to make sure that the behaviors found and the distributions chosen could be better adapted to each other.
By dividing the dataset into categories, we can in fact hope to group behaviors and events with similar distributions so as to make the model more faithful to reality.
Even if the chosen classes do not achieve the desired effect, introducing this possibility in our model benefits its versatility and potentially opens the door to more sophisticated and more performing classifications.

The chosen line of work is to base our classes on easily observable features common to all data in order to maintain the grouping process simple.

The chosen features, although easily obtainable, shall be:
- relevant to the medical field, meaning that they are prone to vary the diseases they might cover or the procedures followed by the hospital staff.
- distinctive enough to split the set of data in comparable portions.

*** WAIT Choosing the classes :traduzione:
Per quanto esistano metodi di classificazione più interessanti (quali ad esempio tutte le [tecniche di clustering], basati generalmente su misurazioni pratiche dei dati) discusse tra i possibili Future Works, abbiamo deciso di basare la nostra classificazione su caratteristiche facilmente osservabili e comuni a tutti i dati, per semplificare il processo di raggruppamento.

# %#TODO: link a pagina wikipedia/paper sulle tecniche di clustering?
# %#TODO: includere link future works?

# Nella sezione [] sono discussi i risultati di questa classificazione.
# %#TODO: classification evaluation.

*** Patient-based classification
# Il primo step di classificazione effettuato è incentrato sui pazienti del Beth Israel Institute.
# Raccogliendo i dati da diverse tabelle contenti informazioni riguardo loro (in particolare le tabelle 'patients' e 'admissions') le features immediatamente disponibili sono:

The first classification step carried out is centered around the patients of the Beth Israel Institute.
If we collect data from different tables containing information about them (in particular the 'patients' and 'admissions' tables) the immediately available features to use for a classification are:
- Their ethnicity
- Their gender
- Their marital status
- Their language

# Di questi abbiamo considerato soltanto il genere e l'etnia del paziente in quanto sono le uniche tra le features proposte che abbiamo ritenuto potessero essere rilevanti in ambito medico.

Of these, we only considered the gender and ethnicity of the patient as they are the only features proposed that we felt could be relevant in the medical field.

# Il legame tra l'etnia e la malattia è da tempo documentato e studiato [si veda [[https://www.ethndis.org/edonline/index.php/ethndis][link]] ] ed è quindi ben nota la sua rilevanza per l'ambito medico.
# Osservando tuttavia le varie categorie disponibili e la distribuzione (mostrata in figura []), risulta evidente che una suddivisione basata sull'etnia risulterebbe errata; Ci sono infatti un numero troppo alto di categorie (aspetto che potrebbe essere sorvolato avendo la possibilità raggruppare ulteriormente le categorie in 'macro-etnie') e uno squilibrio eccessivo nella distribuzione dei pazienti tra le varie categorie (solo la categoria "white" rappresenta circa il 70% della popolazione totale).

The link between ethnicity and disease has been documented and studied for a long time [see [[https://www.ethndis.org/edonline/index.php/ethndisreste][link]]] and therefore its relevance for the medical field.
However, observing the various categories available and the distribution (shown in figure []), it is clear that a subdivision based on ethnicity would be inconclusive; There is in fact a too high number of categories (an aspect that could be overlooked having the possibility to further group the categories into 'macro-ethnic' groups) and an excessive imbalance in the distribution of patients among the various categories (only the "white" category represents approximately 70% of the total population).

# %#TODO: figura ethnicity

# Anche il genere è una caratteristica rilevante in ambito medico: l'incidenza e la gravità con cui si manifestano le malattie varia tra i generi, con alcune (some of them being) sex-specific.

Gender, as previously highlighted, is also a relevant feature in the medical field: the incidence and severity with which diseases occur varies between genders, with some of them being sex-specific.

# Le categorie disponibili in questo caso sono solo due (maschi e femmine) e la distribuzione dei pazienti tra esse è mostrata in figura [].
# Come possiamo vedere, i pazienti sono ben distribuiti tra le due categorie, con il 56% dei pazienti identificati come maschi e il 44% identificate come femmine.

The categories available in this case are only two (male and female) and the distribution of patients among them is shown in figure [].
As we can see, the patients are well distributed between the two categories, with 56% of patients identified as male and 44% identified as female.

# %#TODO: figura genders

**** Non-immediate patients features :traduzione:
# Avendo a disposizione la data di nascita dei pazienti (attributo della tabella `PATIENTS`, come può essere visto []), un'altra feature con una forte rilevanza medica ma non immediatamente disponibile che abbiamo ricavato è l'età del paziente.
Having available the patients' date of birth (an attribute of the `PATIENTS` table, as can be seen []), another feature with strong medical relevance but not readily available that we derived is the patient's age.
# %#TODO: capitolo mimic, sezione tabelle

# La data scelta come riferimento per il calcolo dell'età del paziente (impossibile da considerare in modo assoluto a causa del processo di deidentificazione applicato su MIMIC-III già descritto nel capitolo []) è la data d'inizio della prima permanenza ospedaliera.
The date chosen as the reference for calculating the patient's age (impossible to consider absolutely because of the de-identification process applied on MIMIC-III already described in chapter []) is the date of the beginning of the first hospital stay.
# %#TODO: capitolo design decisions, sezione deidentification

Following this consideration, we can see in figure [] how the patients are distributed in the various age groups.
# %#TODO: Immagine età pazienti (non binned)

# Possiamo vedere che l'età dei pazienti segue una distribuzione pressochè normale centrata sui 70 anni, con un picco considerevole nella fascia d'età tra i 75 e gli 80.

# Durante il processo di deidentificazione applicato su MIMIC sono state contraffatte le informazioni sull'età dei pazienti con 90 anni o più (in quanto categorie relativamente piccole), assegnandogli una data di nascita che risulta in un'età oltre i 300 anni.
# Questi pazienti sono considerati nella fascia d'età '>100', dando una motivazione al picco.

# Prima di poterla considerare come una valida feature di classificazione, è necessario tuttavia ridurre il numero di bin in cui le età sono suddivise (un numero eccessivo di classi porterebbe infatti a insiemi troppo piccoli per essere fit correttamente).

We can see that the age of the patients follows an almost normal distribution centered on 70 years, with a considerable peak in the age range of 75 to 80.

During the de-identification process applied on MIMIC, the age information of patients 90 years or older was de-identified, assigning them a birth date that results in an age over 300 years.
These patients are considered to be in the '>100' age group, giving a rationale for the spike.

Before it can be considered as a valid classification feature, however, it is necessary to reduce the number of bins into which the ages are divided (too many classes would in fact lead to sets that are too small to be fit correctly).

# La suddivisione alternativa scelta copre 5 fasce d'età:
The chosen alternative subdivision covers 5 age groups:
- Up to age 45
- between 45 and 65
- between 65 and 75
- between 75 and 100
- over 100

and results in the distribution shown in Figure [].

# %#TODO: immagine età pazienti (binned)

# I gruppi scelti non sono perfettamente suddivisi, ma hanno rilevanza medica in quanto rappresentano fasce d'età con malattie e disturbi differenti.
# Il gruppo 'over 100' in particolare non è stato aggregato con altri pazienti in quanto rappresenta un'insieme di pazienti con un rischio più alto di decesso ospedaliero.

The groups chosen are not perfectly divided, but they have medical relevance as they represent age groups with different diseases and disorders.
The 'over 100' group in particular was not aggregated with other patients because it represents a group of patients with a higher risk of hospital death.

# %#TODO: non mi convince questa frase.

*** Admission-based classification

The second and last classification step performed is centered around the hospital stays of the Beth Israel Institute.

# Avendo a disposizione a loro riguardo solo le informazioni sulle tempistiche d'inizio e di fine, le uniche features che possiamo estrarre sono quelle non toccate dal processo di deidentificazione, ovvero:
# - il giorno della settimana in cui comincia/finisce la permanenza ospedaliera.
# - l'orario in cui la permanenza ospedaliera inizia/finisce.
# - la stagione approssimativa della permanenza ospedaliera.

# Di queste, abbiamo scelto come feature per la classificazione il giorno della settimana in cui la permanenza ospedaliera ha avuto inizio.

# Osservando la figura [], che rappresenta il numero di admissions registrate per ogni giorno della settimana, si può notare che le admissions sono ben distribuite tra tutti i giorni della settimana, con un repentino abbassamento durante il week end.

Having only information about the start and end times available to them, the only features we can extract are those not touched by the de-identification process, viz:
- the day of the week when the hospital stay begins/ends.
- the time at which the hospital stay begins/ends.
- the approximate season of the hospital stay.

Of these, we chose as a feature for classification the day of the week when the hospital stay began.

Looking at Figure [], which represents the number of hospital stays recorded for each day of the week, we can see that hospital stays are well distributed among all days of the week, with a sudden drop during the weekend.

# %#TODO: figura numero di admissions per weekday

*** Conclusions
# Ricapitolando, abbiamo deciso di attuare le nostre classificazioni sui pazienti e sulle permanenze ospedaliere, mantenendo il focus sul considerare delle suddivisioni eque e collegate alla salute.

To recapitulate, we decided to implement our classifications on patients and hospital stays, keeping the focus on considering fairly split and health-related subdivisions.

# Le features che abbiamo scelto sono state:
# - il giorno della settimana in cui comincia o finisce la permanenza ospedaliera.
# - il genere del paziente.
# - l'età del paziente.

The features we chose were:
- the gender of the patient.
- the age of the patient.
- the day of the week when the hospital stay begins or ends.

# Queste e altre features considerate sono mostrate in tabella [], con indicate le motivazini per cui sono state scelte o meno.

# These and other features considered are shown in table [], with reasons given as to why they were chosen or not.

# %#TODO: Tabella feature-health related-equally splits the dataset

# I risultati delle classificazioni scelte sono mostrati nella tabella [], che mostra il numero di pazienti racchiusi nelle classi identificate a partire dalla classificazione fatta sui pazienti, e nella figura [], la quale mostra la distribuzione delle permanenze ospedaliere tra le varie classi.

The results of the chosen classifications are shown in Table [], which shows the number of patients enclosed in the classes identified from the classification made on the patients, and Figure [], which shows the distribution of hospital stays among the various classes.
# %#TODO: Tabella dati e immagine weekday per classe

# Come possiamo notare, tutti i gruppi hanno pressoché lo stesso numero di elementi, tranne i gruppi relativi alle classi di età '> 100' che come sottolineato in precedenza contengono meno elementi a causa della classe d'età poco popolata.

As we can see, all the groups have a comparable number of items, except for the groups related to the '> 100' age groups, which as pointed out earlier contains fewer items due to the sparsely populated age group

# Tutte le classificazioni, come preannunciato, sono basate su features piuttosto evidenti. Il modello, come vedremo nella sezione [], sarà sviluppato per funzionare anche con classificazioni basate su metodi più complessi (e.g. clustering) che sfruttano caratteristiche più nascoste del modello.

All classifications, as preannounced, are based on rather obvious features.
The model, as we will see in section [], will also be developed to work with classifications based on more complex methods (e.g., clustering) that exploit more hidden features of the model.
# %#TODO: implementation: parlare di come funziona la classificazione e come può essere fatta a livelli diversi.

** Distribution Fitting the identified behaviors :traduzione:
Once the behavior of the patients of the Beth Israel Institute were explored and the model shown in section [1] has been developed the next step is to find the time distributions of each of the behaviors identified.

# %#TODO: sezione precedente sul diagramma delle interazioni

# Le classi indicate nella sezione [] che partizionano l'insieme dei pazienti e delle permanenze ospedaliere sono considerate nel fitting delle tempistiche precedentemente identificate, ma non in tutte: le attività identificate nell'activity diagram [] che indicano casi limite, a causa della scarsità di sample a dispozione, non possono essere suddivise in classi.
The classes shown in section [] that partition the set of patients and hospital stays are considered in fitting the previously identified timings, but not in all of them: the activities identified in the activity diagram [] that indicate borderline cases, due to the scarcity of available samples, cannot be partitioned into classes.
# %#TODO: link action diagram

# L'unico caso limite non affetto da questa regola è l'intertempo tra le permanenze ospedaliere, che pur rappresentando una casistica diminuita (la maggior parte dei pazienti effettua una singola permanenza ospedaliera come si può vedere in figura []), abbiamo deciso di applicare su di esso solo la classificazione basata sui pazienti (non essendo collegato a una sola permanenza ospedaliera).
The only borderline case that is not affected by this rule is the time between hospital stays, which although it represents a decreased caseload (most patients make a single hospital stay as can be seen in figure []), we decided to apply just the patient-based classification on it (as it is not related to a single hospital stay).
# %#TODO: figura admissions per paziente

# Per riassumere, la tabella [] mostra quali classi sono state considerate per ciascuna attività.
To summarize, Table [] shows which classes were considered for each of the previously identified activities.
# %#TODO: tabella attività/classi, con 2 colonne (attività, tipo classi considerate, totale classi considerate)

*** Metodologia
# Per effettuare il fitting degli intervalli di tempo identificati, abbiamo utilizzato delle distribuzioni di tipo Phase Type, utilizzando in particolare distribuzioni Hyper-erlang (see []).
To perform the fitting of the identified time intervals, we used Phase Type distributions, specifically Hyper-erlang distributions (see []).
# %#TODO: link background phase type

# Queste sono comunemente utilizzate nell'ambito della simulazione in quanto dotate della desiderabile caratteristica di poter approssimare qualsiasi distribuzione con precisione arbitraria [].
These are commonly used in simulation as they have the desirable characteristic of being able to approximate any distribution with arbitrary precision [].
# %#TODO: cit versatilità

# Lo strumento utilizzato per il fitting di queste distribuzioni è stato HyperStar, a tool for fitting phase-type distributions to data sets designed with user-friendliness and simplicity in mind.
The tool used for fitting these distributions was HyperStar, a tool for fitting phase-type distributions to data sets, designed with simplicity and ease of use in mind.

# Come spiegato in precedenza nella sezione [], HyperStar non è un tool automatizzato: richiede infatti una fase di interazione con l'utente per permettere una corretta approssimaizione della data trace fornita.
As explained earlier in section [], HyperStar is not an automated tool: in fact, it requires a user interaction step to allow a correct approximation of the provided data trace.
# %#TODO: sezione hyperstar

# Avendo identificato 4 tipologie di comportamento su cui applicare la classificazione e avendo introdotto un numero considerevole di classi in cui ogni comportamento è suddiviso, il tempo richiesto per il fitting sarebbe stato eccessivo.
Having identified 4 types of behavior on which to apply the classification and having introduced a considerable number of classes into which each behavior is divided, the time required for fitting would have been excessive.
# %#TODO: sezione conlcusioni classificazione e sezione conclusioni di analisi delle interazioni

# Per ovviare a questo inconveniente, abbiamo scelto di raggruppare le classi di ogni comportamento che appartengono alla stessa distribuzione, così da poter ridurre il numero di distribuzioni da fittare attraverso HyperStar.
To overcome this drawback, we chose to group the classes of each behavior that belong to the same distribution, so that we could reduce the number of distributions to fit through HyperStar.

# Questa scelta risulta ancora più sensata se si considera che le classi trovate, come detto in precedenza, sono basate su feature evidenti dei pazienti e delle permanenze ospedaliere e non precludono quindi la possibilità che alcune di esse seguano la stessa distribuzione tra una classe e l'altra.
This choice makes sense if we consider that the classes found, as mentioned earlier, are based on obvious features of patients and hospital stays and thus do not preclude the possibility of some of them following the same distribution between classes.

**** Raggruppamento delle classi
# Per confrontare tracce di dati empirici e decidere se provengono dalla stessa distribuzione abbiamo utilizzato il test Kolmogorov-Smirnov per 2 samples.
To compare empirical data traces and decide whether they are sampled from the same distribution, we used the Kolmogorov-Smirnov 2-samples test, described fully in section [].
# Questo test, descritto più a fondo nella sezione [], ci fornisce la probabilità minima che due tracce di dati provengano dalla medesima (anche se sconosciuta) distribuzione.
This test, described more completely in section [], returns the minimum probability that two data traces come from the same (although unknown) distribution.


# si occupa di verificare l'ipotesi statistica che i dati provengano dalla stessa distribuzione.
# %#TODO: 2-sample test kolmogorov-smirnov. Vedi tesi clau per un riferimento a come descriverlo.

# La libreria utilizzata per effettuare il test tra le distribuzioni disponibili è la libreria python scipy, che nel suo modulo

# Essendo il metodo limitato a due samples, l'abbiamo applicato a tutte le possibili coppie di classi

# Posto un limite minimo \alpha oltre la quale il test è considerato avere esito positivo e applicandolo a tutte le possibili coppie di classi, siamo in grado di identificare quali di queste risultano avere una CDF (cumulative density function) simile, ottenendo quindi la possibilità di raggrupparle per farne il fitting come un'unica distribuzione.
Once a lower probability limit \alpha beyond which the test is considered to be successful is set and after it is applied to all possible pairs of classes, we are able to identify which of them have a similar empirical cumulative density function, thus enabling to group them to be fit as a single distribution.

# Tuttavia, è necessario tenere a mente che i risultati del test non sono transitivi: se la classe 'A' supera la soglia \alpha quando confrontata con la classe 'B' e la classe 'B' supera la soglia quando confrontata con la classe 'C', ciò non implica che il risultato del test applicato tra la classe 'A' e la classe 'C' superi la stessa soglia \alpha.
However, it should be kept in mind that the test results are not transitive: if class 'A' exceeds the threshold \alpha when compared with class 'B' (marking them as having the same distribution) and class 'B' exceeds the threshold when compared with class 'C,' it does not imply that the test result applied between class 'A' and class 'C' exceeds the same threshold \alpha.

# Per questo motivo, abbiamo deciso di considerare un'unica distribuzione solo per gli insiemi di classi in cui il test di Kolmogorov-Smirnov superasse la soglia \alpha per ogni coppia di classi all'interno.
For this reason, we decided to group into a single distribution only sets of classes in which the Kolmogorov-Smirnov test exceeded the threshold \alpha for each pair of classes within.

# Se rappresentiamo le classi disponibili come nodi di un grafo non direzionato e colleghiamo con degli archi solo le coppie che hanno superato il test, possiamo identificare gli insieme sopracitati come le

# Per ottenere gli insiemi sopracitati, abbiamo utilizzato il seguente metodo, che sfrutta i concetti della teoria dei grafi:
To obtain the aforementioned sets, we used the following method, which exploits the concept of maximal complete subgraph in graph theory:
# - Rappresentiamo le classi disponibili come nodi di un grafo non direzionato (fig []).
# - Colleghiamo con archi solo le coppie che hanno superato la soglia \alpha nel test Kolmogorov-Smirnov (fig []).
# - Identifichiamo i sottografi completi massimali all'interno del grafo (fig []).
#   # tramite la libreria networkx ?
# - Nel caso in cui uno o più dei nodi considerati appartengano a più sottografi completi massimali contemporaneamente, non volendoli considerare in più distribuzioni distrinte, assegnamoli solo al sottografo completo massimale con il maggior numero di nodi (fig []). Grazie alla loro completezza, gli altri sottografi completi rimarranno tali (o, al più, vuoti) anche dopo la rimozione del nodo incriminato.
1. Represent the available classes as nodes of an undirected graph (fig []).
2. Connect with arcs only those pairs that exceeded the \alpha threshold in the Kolmogorov-Smirnov test (fig []).
3. Identify the maximal complete subgraphs within the graph (fig []).
4. In the case where one or more of the nodes considered belong to several maximal complete subgraphs at the same time, since they cannot be considered in multiple distinct distributions, assign them only to the maximal complete subgraph with the largest number of nodes (fig []). Due to their completeness, the other complete subgraphs will remain as such (or, at most, empty) even after removal of the offending node.
# %#TODO: figure preparate
# L'algoritmo appena mostrato non copre tutti i casi limiti (come il caso in cui i vari )

# Raggruppando i
# In Table [] sono mostrati i risultati del raggruppamento consideranto un limite alpha di 0.05 per ogni tipo di comportamento su cui il raggruppamento è stato applicato, mostrando in particolare la riduzione del numero di classi da considerare.
Table [] shows the results of the grouping method described above considering an alpha limit of 0.05 applied on each kind of behavior on which a grouping was meant to be applied, showing in particular the reduction in the number of classes to be considered.
# %#TODO: tabella con il numero di classi identificate per ogni gruppo
| time intervals                    | classi prima del raggruppamento | gruppi formati |
|-----------------------------------+---------------------------------+----------------|
| time after the last icu has ended |                              70 |             21 |
| time before the icu starts        |                              70 |             27 |
| time in ICU                       |                              70 |             22 |
|-----------------------------------+---------------------------------+----------------|
| TOTAL                             |                             210 |             70 |

# Per ogni gruppo individuato abbiamo raccolto i samples dei time interval per tutte le classi appartenenti al gruppo, utilizzandoli per fittare una distribuzione tramite HyperStar; Il mapping tra la classe e il gruppo d'appartenenza è stato salvato in un file csv.
For each group identified, we collected time interval samples for all classes belonging to the group and used them to fit a distribution using HyperStar; The mapping between the class and the group to which it belongs was saved in a csv file.

# Un esempio del risultato della procedura di raggruppamento è mostrato in figura [] dove possiamo vedere che, considerando il tempo di permanenza in ICU, tre classi sono state raggruppate e fittate in un'unica distribuzione (mostrata in figura con una linea tratteggiata).
An example of the result of the grouping procedure is shown in figure [] where we can see that, considering the time spent in the ICU, three classes were clustered and fitted into a single distribution (shown in figure with a dashed line).
# %#TODO: figura grouping example.

** Distribution Fitting the events
# Come accennato in precedenza nella sezione [], durante ciascuno degli intervalli di tempo individuati sono generati eventi appartenenti a due possibili categorie:
As mentioned earlier in section [], events belonging to two possible categories are generated during each of the identified time intervals:
# - eventi collegati ad una permanenza ospedaliera
# - eventi collegati ad una permanenza in ICU
- events related to a hospital stay
- events related to an ICU stay
# %#TODO: sezione default behavior

# Come per il caso dei comportamenti dei pazienti, anche questi eventi richiedono di essere fittati a delle distribuzioni per poter essere simulati.
As with the case of the behaviors of the patients, these events also require to be fit to distributions in order to be simulated.

# Le classi individuate nella sezione [] sono applicate anche in questo caso per effettuare il fitting della distribuzione degli eventi identificati.

*** The chosen distribution

# A causa dei processi di deidentificazione applicati su MIMIC-III presentati in [], siamo costretti a considerare per il fitting i tempi di inter-arrivo tra due eventi successivi.
Due to the de-identification processes applied on MIMIC-III presented in [], we are forced to consider for our fitting purposes the inter-arrival times between two successive events.
# %#TODO: sezione deidentificazione mimic

# La distribuzione scelta per modellarli è la distribuzione esponenziale.
# Essa è stata scelta in quanto comunemente utilizzata per rappresentare il tempo di inter-arrivo in un processo di Poisson omogeneo, a sua volta comunemente usato per rappresentare processi randomici che occorrono nella vita di tutti i giorni [cit].
The distribution chosen to model them is the exponential distribution.
It was chosen because it is commonly used to represent the inter-arrival time in a homogeneous Poisson process, which in turn is commonly used to represent random processes that occur in everyday life [cit].
# %#TODO: citazione "Simulating the Poisson Process", P.Mcquighan

# Avremmo potuto utilizzare delle distribuzioni di tipo phase-type come visto in sezione [], ma il numero elevato di eventi su cui il fitting doveva essere effettuato e il numero di classi prese in considerazione, combinato al tempo utente necessario per effettuare il fitting tramite HyperStar presentato in precedenza nella sezione [], avrebbero richiesto un tempo eccessivo.
We could have used phase-type distributions as seen in section [], but the large number of events on which the fitting had to be performed and the number of classes considered, combined with the time required to perform the fitting via HyperStar presented earlier in section [], would have taken an excessive amount of time.
# %#TODO: sezione fitting behavior
# %#TODO: problema hyperstar

# L'aderenza alla realtà, per quanto una caratteristica desiderabile, non è il focus principale del lavoro, come invece lo è l'estensibilità.
# La possibilità di utilizzare distribuzioni differenti e

# D'altro canto, per effettuare il fitting attraverso delle distribuzioni esponenziali, l'unica necessità
On the other hand, most of the methods commonly used to perform the fitting of an exponential distribution can be easily automated and don't require excessive computational power to be performed.

# Il fitting di distribuzioni esponenziali può essere effettuato tramite diversi metodi (least squares method, maximum likelihood, moments method); Dato che nella letteratura [] i fitting evidenziati come più imparziali sono il metodo dei momenti e il maximum likelihood method, abbiamo deciso di applicare il metodo dei momenti per effettuare il fitting.
Indeed, the fitting of exponential distributions can be carried out with several methods (least squares method, maximum likelihood, moments method); Since in the literature [] the fittings highlighted as most unbiased are the method of moments and the maximum likelihood method, we decided to apply the method of moments to carry out the fitting.
# %#TODO: Fitting an Exponential Distribution (ROBERTO FRAILE AND EDUARDO GARCÍA-ORTEGA)

# Il metodo dei momenti consiste nello stimare i parametri della distribuzione da fittare confrontando ciascun momento empirico registrato dai samples con il momento della distribuzione.
The method of moments consists in the estimation of the parameters of the distribution to be fit by comparing each empirical moment recorded from the samples with the analytical moment of the distribution.

# Nel caso dell'intertempo tra gli eventi di un processo di Poisson, espresso secondo la formula [], l'unico parametro da stimare è $\lambda$ e, per tanto, basta utilizzare il primo momento empirico dei samples considerati per ricavarlo.
In the case of the intertime between events of a Poisson process, expressed according to the formula [], the only parameter to be estimated is $\lambda$ and, therefore, it is sufficient to use the first empirical moment of the considered samples to derive it.
# %#TODO: funzione esponenziale

# Essendo il primo momento di un esponenziale [], è sufficiente ricavare l'inverso la media (a.k.a. primo momento) della traccia di dati considerata per stimare il parametro da utilizzare e, di conseguenza, ottenere la distribuzione fit.
Since the first moment of an exponential is [], it is sufficient to derive the inverse of the mean (a.k.a. first moment) of the considered data trace to estimate the parameter to be used and, consequently, obtain the fit distribution.
# %#TODO: primo momento esponenziale

# Questo processo, come evidente, è facilmente automatizzabile una volta ottenuti gli inter-tempi dell'evento preso in considerazione.
This process can clearly be easily automated once the inter-arrival times of the event under consideration are obtained.

# Tuttavia, non essendo il focus di MIMIC sulla valutazione temporale delle interazioni tra i pazienti e il sistema ospedaliero, non esiste un'indicazione comune a tutti gli eventi dell'istante temporale in cui l'evento è accaduto.
Nonetheless, since the focus of MIMIC is not on the temporal assessment of interactions between patients and the hospital system, there is no common indication for all events of the time instant at which the event occurred.
# Invece, alcuni eventi hanno a disposizione il `charttime`, ovvero l'istante temporale in cui l'evento è stato osservato; altri hanno a disposizione uno `storetime`, ovvero l'istante temporale in cui l'evento è stato introdotto nel sistema ospedaliero; Altri ancora hanno altre indicazioni temporali, e vanno considerati separatamente.
Instead, some events have a `CHARTTIME` available, which is the time instant at which the event was observed; others have a `STORETIME` available, which is the time instant at which the event was introduced into the hospital system; Others again have other time indications, and should be considered separately.

# Nelle sezioni seguenti, analizzeremo caso per caso ciascuno degli eventi che siamo interessati a simulare, mostrando quali attributi dell'evento abbiamo considerato per ricavarne le tempistiche e soffermandoci sui casi particolari che hanno richiesto studi più approfonditi.
# Per un riferimento più completo, una lista delle tabelle contenute in MIMIC-III e degli eventi ad esse collegati può essere trovata nella sezione [].
# %#TODO: sezione MIMIC

*** Methodology

# La procedura standard applicata per il fitting di un'esponenziale a ciascuna tipologia di evento è la seguente:
The standard procedure applied for fitting an exponential to each type of event is as follows:
# - ottengo gli eventi di quella categoria
# - li suddivido per classi
# - ne calcolo l'intertempo basandomi sull'attributo in grado di darmi l'indicazione temporale più precisa
# - trovo la media del sample raccolto
# - utilizzo la media trovata per stimare il parametro lambda di un'esponenziale tramite il metodo dei momenti visto in precedenza.
- I get the events in that category
- I split them by the classes identified in section []
- I compute their intertime based on the attribute that can give me the most accurate time stamp
- I find the average of the collected samples
- I use the average found to estimate the lambda parameter of an exponential via the method of moments described earlier.
# %#TODO: sezione classification

# Quello che ottengo è, per ogni tipologia d'evento, un'esponenziale fitted ad ogni classe.
# Per buona parte degli eventi considerati, la metodologia indicata sopra è sufficiente, e in tabella [] sono indicati gli attributi utilizzati per effettuare il fitting.
# Come si può notare, quando possibile è stato prediletto l'uso dell'attributo 'storetime' rispetto ad altri attributi disponibili, in quanto indicativo dell'effettiva interazione con il sistema ospedaliero e quindi più specifico per il caso d'uso proposto.
What I obtain is, for each kind of event, a fitted exponential to each class.
For most of the events considered, the methodology given above is sufficient, and Table [] shows the attributes used to perform the fitting.
As can be seen, when available the attribute 'storetime' was preferred over other available attributes, as it is indicative of the actual interaction with the hospital system and therefore more specific to the proposed use case.
# %#TODO: table evento-attributo

# I casi non coperti dalla procedura appena vista sono presentati nelle seguenti sezioni.
Cases not covered by the procedure just seen are presented in the following sections.

**** CPT Events and Prescription Events
The CPTEVENTS table contains a list of which current procedural terminology codes were billed for which patients.
As shown in section [], these events may happen at any time during the hospital stay.
# L'unica informazione temporale disponibile su questi eventi è fornita dall'attributo `CHARTDATE` il quale (come il nome lascia intendere) fornisce una data ma non un'indicazione temporale precisa.
The only temporal information available about these events is provided by the `CHARTDATE` attribute, which (as the name implies) provides a date but not a precise time stamp.

# La stessa situazione vale per gli eventi segnati nella tabella `PRESCRIPTION` i quali, pur avendo a disposizione gli attributi `STARTDATE` e `ENDDATE` ad indicare la data di inizio e fine della prescrizione medica non hanno a disposizione indicazioni più precise riguardanti l'istante temporale in cui sono stati registrati.
The same situation applies to events marked in the `PRESCRIPTION` table which, although they have the attributes `STARTDATE` and `ENDDATE` available to indicate the start and end date of the prescription, do not have more precise indications regarding the time instant at which they were recorded.

**** Callout Events
The `CALLOUT` table provides information about ICU discharge planning. When a patient is deemed ready to leave the ICU, they are “called out”. This process involves:
- a care provider registering that the patient is ready to leave the ICU and detailing any specialized precautions required
- a coordinator acknowledging the patient requires a bed outside the ward a variable period of time in order to coordinate the transfer
- an outcome: either the patient is called out (discharged) or the call out event is canceled

Each of the steps listed above involves an interaction with the hospital system at different times, recorded in the `CALLOUTS` table through the following attributes:
- `createtime` provides the time at which the registration of the callout request was performed.
- `acknowledgetime` is the time at which the coordinator acknowledged the callout.
- `updatetime` provides the last time at which the callout event was updated.
- `outcometime` is the time at which the outcome of the callout was registered.

The only attributes that are ensured to be registered for each outcome are `createtime` and `outcometime` and, as such, they are the only ones we considered during this analysis.

We opted to model the outcome and the creation of the callout as two distinct events, but related to one another.

In fact, while the creation of the callout was modeled with the same standard procedure explained previously, where the time between callout creations was taken as the interval to model, the outcome of the callout was modeled using the time between the creation of the callout and the outcome of the same callout;
This way, during the generation procedure that will be shown in section [], when the generation of the callout event is performed, we can generate the associated outcome event.

Figure [] summarises what time intervals are considered for fitting both outcome and creation events.
# %#TODO: implementation section

**** Input Events
# Le tabelle INPUTEVENTS_MV e INPUTEVENTS_CV tengono traccia dei fluidi somministrati ai pazienti durante ciascuna loro permanenza in ICU. Le due tabelle rappresentano i dati raccolti da due critical care information systems distinti, namely CareVue e Metavision.
Tables `INPUTEVENTS_MV` and `INPUTEVENTS_CV` track the fluids administered to patients during each of their ICU stays. The two tables represent data collected from two separate critical care information systems, namely CareVue and Metavision.
# A causa di discrepanze nella modalità di storage dei dati, le due tabelle could not be integrated. Essendo tuttavia il nostro lavoro incentrato sullo studio delle tempistiche delle interazioni con il sistema ospedaliero e possedendo entambe le tabelle l'attributo `storetime` contenente la tempistica della registrazione nel sistema ospedaliero dell'evento, le due tabelle sono state considerate assieme.
Due to discrepancies in the way the data from the two tables was stored, they could not be integrated.
However, since our work is focused on studying the timing of interactions with the hospital system and since both tables possess the `STORETIME` attribute containing the time stamp of the recording in the hospital system of the event, the two tables were considered together during fitting.
# Il metodo poi seguito per il fitting degli eventi raccolti è stato lo stesso visto nella procedura standard presentata in precedenza.
The method then followed for fitting the collected events was the same as seen in the standard procedure presented earlier.

**** Transfer Events
The `TRANSFERS` table monitors the location of the patients throughout their hospital stay. The ICUSTAYS table is derived from this table, but multiple transfer events might happen during the same stay in ICU.

Each transfer event is associated with an `INTIME` and an `OUTTIME` that represent the amount of time the patient stayed in the  considered ICU ward.
Due to the way the table is constructed, there's no time interval between the outtime of a transfer and the intime of the next transfer during the same ICU stay.

We opted to model the transfer events with a single time reference that represents the time at which the transfer happened during the single ICU stay.
The time interval used to model the transfer events is the interval between the intime and the outtime of the transfer during the same ICU stay.
During the generation of the events, the generated time interval was corrected to avoid transfers for a certain ICU stay happening outside of the time dedicated to the ICU stay.

**** Note Events
The `NOTEEVENTS` table contains all notes written by the medical staff of the medical institute for their patients. This kind of events, due to their natural language constitution, represents a first important example of heterogeneous data stored in the hospital system of the Beth Israel Medical Institute and recorded by MIMIC.

# Nonostante non sono fornite informazioni riguardo il loro processing all'interno del sistema ospedaliero, possiamo facilmente ipotizzare che subiscano un trattamento di rilievo all'interno del sistema ospedaliero. Per questo motivo, abbiamo trovato di particolare importanza modellarli correttamente.
As many other tables, NOTEEVENTS has available both a `CHARTTIME` attribute and a `STORETIME` attribute.
Although in these cases we usually prefer to consider the `STORETIME` attribute as more reliable, MIMIC-III's documentation clearly states that certain kinds of medical notes (namely discharge summaries, ECG notes, radiology notes, and echo notes) don't have a `STORETIME` associated but only a `CHARTTIME`[cit].
# %#TODO: citation required: mimic documentation
For this reason, we opted to consider the `STORETIME` attribute when available as a valid time indication and, otherwise, to use the `CHARTTIME` attribute.

The way Note events are fit does not otherwise change over the standard procedure previously presented.

*** Fitting the waveforms
Although not events registered in MIMIC-III, Waveforms pose another important source of data.
Due to their structure fundamentally different than the rest of the data set, they had to be preprocessed as shown in section [] to make a correct time model about them.
# %#TODO: Waveforms preprocessing section

The results of the preprocessing procedure are in the form of a table that captures the duration of each trasmission slot, the number of transmissisons performed during the slot, the signals recorded in the system for each transmission and the length of the pauses between each transmission slot.

The objective distribution we wanted to fit were:
- The duration of the pauses
- The duration of the transmission slots.

Both of these distributions were split into the classes found in section [] and fit with an exponential distribution through the method of moments (as the case with all the events presented in section []) described previously.
# %#TODO: sezione classificaziont + sezione precedente con tutti gli eventi.

In order to make our simulator richer and more featureful, we also leveraged the information gathered during the preprocessing phase to include in each generated transmission the signals it would have registered in the data system.

In this regard, the probability of each transmission to carry a certain signal was computed by checking the number of transmissions carrying that signal in the considered group against the total number of transmission in the group.
