#+title: Analysis

* TODO Introduzione

* Analisys of the interactions

** Why? :traduzione:
# Volendo modellare e riprodurre il flusso di dati tra il paziente e il sistema ospedaliero di cui mimic ci fornisce uno squarcio, è utilie, come prima cosa, cercare di individuare il pattern di interazione tra utenti e ospedale.

Since we wanted to model and reproduce the stram of information between the patient and the hospital system of which Mimic gives us a glimpse, it is useful, as a first step, to try and understand the registered behavior of the users in the hospital system.

** Default interactions :traduzione:
As introduced in section X, MIMIC-III focuses on the interactions of the patients who stayed in _critical care units_ of the Beth Israel Deaconess Medical Center.

# Oltre a contenere le informazioni sulle permanenze in ICU dei pazienti (quali ad esempio data e ora di inizio e fine della icy stay) ha anche informazioni riguardati la loro intera permanenza ospedaliera fuori dai reparti di terapia intensiva.

Other than informations about the ICU stays of the patients, like date and time of start and finish of the ICU stay, MIMIC also contains informations about their entire hospital stay, spanning their time outside the intensive care units.

# Alcune tipologie di eventi sono collegate a (e avvengono durante) una permanenza in ICU, mentre altre sono invece associate all'intera permanenza ospedaliera.
# Per questo motivo, è importante definire i periodi in cui ciascuna di queste tipologie di eventi viene generata.

Some kind of events are associated to (and happen during) an ICU stay, while others are associated to the entire hospital stay.

# Utilizzando i termini di MIMIC, diremo che il paziente è associato a una Admission dal momento in cui viene generato l'evento che segnala l'inizio della permanenza ospedaliera a quando viene segnata la fine della permanenza, mentre diremo che il paziente è associato a una ICU stay quando viene generato l'evento che segnala l'inizio della permanenza in ICU.
# TODO: capitolo MIMIC

Using some MIMIC terminology, we will say an event is "associated to an admission (or an hospital stay)" when it has the "hadm_id" attribute, that is to say that is was registered during the time when the hospital stay took place, while we will say that the event is "associated to an icustay" when it possesses the attribute "icustay_id", that is to say it was registered during the time when the patient was in an ICU.
As one can guess, every event is associated to an hadm_id, since all registered events happened during an hospital stay, but only some categories of events have an icustay_id associated.
For additional information about the structure of MIMIC, please refer to link

# %#TODO: capitolo mimic

# Una prima approssimazione del comportamento dei pazienti può essere la seguente:

# - Dopo l'inizio della permanenza ospedaliera, c'é un periodo di tempo prima dell'inizio della permanenza in ICU del paziente in cui il paziente è associato a un'admission ma non a una ICUstay.
# - Il paziente viene quindi ammesso in una ICU, dove comincia la sua ICU stay. Durante questo periodo, sono generati gli eventi associati alla ICU stay.
# - Il paziente esce dall'ICU
# - Dopo un periodo di tempo fuori dall'ICU, si conclude la sua admission.

# In tutti questi periodi di tempo, il paziente ha continuato a generare eventi legati alla sua admission.

# Le interazioni appena descritte sono formalizzate nel seguente UML activity diagram (gli elementi formali degli activity diagram sono descritti in link )

A first approximation of the behavior of the patients inside the system could be the following:

- After the hospital stay has started, there's a time period before the start of the ICU stay of the patient in which she is associated to an hospital stay but not to an ICU stay.
- The patient then gets admitted into an intensive care unit, where her ICU stay starts. During the period inside the ICU, the events associated to the ICU stay are generated.
- The patient then exits the intensive care unit.
- After a period of time outside the ICU, her admission terminates.

During this whole time, the patients continues to generate events associated to her admission.

The behavior described above can be formalized in the following UML activity diagram (the specification for UML activity diagrams can be found at link)

# %#TODO: insert link to UML activity diagram sprcification

# %#TODO: UML activity diagram base

** Refinements on the interaction model
# Il modello appena visto può essere migliorato facendo alcune considerazioni riguardanti MIMIC e confrontandole con i dati contenuti in esso.
The model just seen can be improved by making some hypotheses regarding MIMIC and comparing them with the data contained in it.

*** Multiple hospitalizations and multiple ICU stays

# Una delle prime considerazioni fatte ha introdotto la possibilità che lo stesso paziente avesse molteplici admissions e, all'interno della stessa permanenza ospedaliera, molteplici ICU stays.
# Le analisi fatte su MIMIC a riguardo hanno dato supporto a queste ipotesi, come mostrano i grafici riportati sotto:

One of the first considerations made introduced the possibility for the same patient to have multiple hospital stays and, during the same hospital stay, multiple ICU stays.
The analyzes made on MIMIC-III on this regard were made supported the hypotesis, as shown in the following figures.
# %#TODO: grafico admissions_amount.png
# %#TODO: grafico icustays_amount.png

# Come possiamo vedere, nonostante la maggioranza dei pazienti abbia una sola permanenza ospedaliera registrata e una singola permanenza in ICU, una porzione non trascurabile hanno molteplici admissions associate o molteplici icu stays associate alla stessa permanenza ospedaliera.

As we can see, even though the majority of the patients is associated to a single hospital stay and most hospital stays are associated to a single ICU stay, a non-negligible portion of patients has multiple admissions associated or multiple ICU stays associated to the same hospital stay.

# Visti questi risultati, è utile modificare il nostro modello delle interazioni per tenere in considerazione i pazienti sopra citati.
# L'activity diagram mostrato di seguito mostra il nuovo modello, considerando la possibilità che l'admission si ripeta o che ci sia un ulteriore permanenza in ICU oltre la prima.

Given these results, it is useful to update our patient behavior model to consider the patients mentioned above.
The activity diagram shown below shows the new model, that consdiers the possibility for an hospital stay to repeat and for another ICU stay other than the first to happen.

# %#TODO: activity diagram 2

# Come si può notare, tra permanenze ICU successive viene considerato un intervallo di tempo, denominato nel diagramma "wait time between icu stays".
# Questo periodo di tempo poteva non essere considerato separatamente dall'azione "wait after the ICU stay", ma abbiamo deciso di considerarli separamente già a questo stadio nell'eventualità che avessero una distribuzione differente.

As you can see, between successive ICU stays a time interval is considered, labeled in the diagram as "wait time between ICU stays".
This time period could be considered in conjunction with the period after the ICU stay shown in the previous version of the model, but we decided to consider them separately in the event that they have a different time distribution.


*** HOLD ICU stays that start immediately
Non le abbiamo considerate alla fine, ma possiamo mostrare che alcune partono dopo pochissimo tempo.

*** Hospitalizations that end immediately after discharge from ICU
# Analizzando MIMIC alla ricerca di comportamenti fuori dallo standard abbiamo notato che un numero importante di permanenze ICU finisce dopo la permanenza ospedaliera a cui sono collegati (12762 permanenze in ICU su 61532).
# Come possiamo notare nel grafico sotto, che rappresenta la cumulative density function delle icustays "anomale", la maggior parte di esse ha al più un giorno di distanza dalla fine della admission ad essa collegata, con oltre il 75% al di sotto della soglia delle 3 ore.

During the analysis of MIMIC-III, looking for outstanding behaviors, we noticed that an important number of ICU stays (12762 of 61532) finish after the hospital stay to which they are associated (through the `icustays` table).
# %#TODO: mimic
As we can notice in the figure below, which represents the comulative density function of the abnormal icustays, the majority of them has at most one day of time distance after the end of the associated hospitalization, with over 75% below three hours.

# %#TODO: image: icustays-end-before-admissions_cdf

# Non avendo trovato informazioni a riguardo nella documentazione di MIMIC-III, per evitare che venissero perse o considerate scorrettamente successivamente, abbiamo deciso di considerarle come la fine reale delle permanenze ospedaliere.

Since we were not able to find informations about them in MIMIC-III's documentation, to prevent them from being lost or incorrectly considered later on, we decided to include them as the real finish time of the associated hospital stays.

# In accordo con questa considerazione, visto l'alto numero di permanenze ospedaliere che terminano immediatamente dopo la permanenza in ICU, abbiamo ritenuto opportuno considerare questa opportunità separatamente, introducendola nel nostro modello.
In accordance with this consideration and given the high number of hospital stays that finish immediately after the last ICU stay, we deemed it appropriate to consider this possibility separately by explicitly introducing it in our model.

# L'activity diagram aggiornato è mostrato di seguito:

The updated activity diagram is shown in the following figure.

# %#TODO: activity diagram

*** HOLD Hospitalizations that don't have an ICU stay

# Nel cercare informazioni aggiuntive riguardanti MIMIC, abbiamo trovato un altro caso limite, anche se meno evidente dei precedenti: una piccola porzione delle permanenze ospedaliere (1190 su 58976, corrispondente al 2%) non è associata con alcuna permanenza icu nella tabella ICUSTAYS di MIMIC-III (vedi la sezione [] per riguardanti le tabelle di mimic).

While looking for additional informations in MIMIC, we found another limit case, less evident than the ones previously considered: A small portion of the hospital stays (1190 over 58976, 2%) is not associated to any ICU stay in the ICUSTAYS table of MIMIC-III (see section [] for a presentation of the tables that comprise MIMIC-III).
# %#TODO: mimic

Although they do not represent a big portion of the cases considered (but still a significant one), due to their outstanding behavior we deemed useful to consider these admissions separately in our model, of which you can see the updated version below.

# %#TODO: diagramma noicu

# Alla fine del percorso di sviluppo del modello (quasi per caso) ci siamo resi conto del fatto che questa caratteristica fuori dalla norma per un dataset specializzato sulle permanenze in ICU è effettivamente un caso particolare: Queste permanenze ospedaliere erano collegate a degli eventi a loro volta associati a una permanenza in ICU, ma tale permanenza in ICU, nella tabella ICUSTAYS, era associata a una permanenza ospedaliera differente (anche se dello stesso paziente);
# Questa casistica non è sottolineata nella documentazione di MIMIC e mette in dubbio il fatto che durante alcune permanenze ospedaliere possano non avvenire icustays.

During the final stages of the development process for the model, we realized that this outstanding characteristic was indeed a peculiar case: the hospital stays described above are connected with some events, which in turn are associated to some icu stays, but these icu stays are associated to a different hospital stay (from the same patient) in the ICUSTAYS table;
This possibility is not described in MIMIC's documentation, and jeopardizes the correctness of the updated model.

# Essendo uno dei principali obiettivi del nostro modello la riusabilità (come sottolineato nella sezione []), abbiamo deciso di mantenere questa casistica in quanto, considerando un caso più generico, possiamo comunque assumere che durante alcune permanenze ospedaliere i pazienti non permangano in una ICU.

Since one of the main objective of our model is reusability though (as explained in section []), we decided to keep the modifications applied. After all, if we considered a more general case that did not cover only ICU patients, we could safely assume that some hospital stays would not result in an ICU stay.
# %#TODO: sezione design decisions

The activity updated activity diagram is shown in the figure below.

# %#TODO: activity diagram

*** Conclusion
In the model whose development was shown in this section we identified a total of 5 time intervals:
- The time in ICU, in which the events associated with the ICU are created.
- The time waiting before an admission and the first ICU stay
- The time between two consecutive ICU stays.
- The time between the end of the last ICU stay and the end of the entire hospital stay.
- The total time in the hospital, which shall be considered as the sum of the times listed above.

The next step in our analysis is to find the distributions that correctly fit each of these time intervals (except the last one, which can be derived from the others).

** Fitting the interactions
Once the behavior of the patients of the Beth Israel Institute were explored and the model shown in section [1] has been developed, the next step is to find the distributions of each of the time intervals identified.

# %#TODO: sezione precedente sul diagramma delle interazioni
