#+title: Background

* K-S test
The Kolmogorov-Smirnov test for two samples is a non-parametric statistical test used to compare those samples and assess whether they were extracted from the same continuous distribution.

To do so, the test computes the maximal distance between the cumulative empirical distribution functions (abbreviated ECDF) of the two samples, a function that associates to each observation x_i the sum of the ratios between the absolute value frequency and the cardinality of the sample.

If such maximal distance is bigger than the critical value /D/, where
# formula
the Kolmogorov-Smirnov test rejects the null hypothesis that the two samples are extracted from the same distribution.

The parameter $\alpha$ that appears in the formula for the critical value D is the significance level of the test, which indicates the maximum probability that the test will result in a false negative (the two samples come from the same distribution, but the test fails to detect it).
The parameter /n/ and /m/ represent the cardinality of the two samples.
# hai usato la libreria scipy.
