#+title: Background

The Kolmogorov-Smirnov test for two samples is a nonparametric statistical test used to test wether two underlying one-dimensional probability distributions differ.
In particular, the test can be used to compare two samples to asses wether they were extracted from the same distribution or not.

To do so, the test leverages the Kolmogorov-Smirnov statistic, which quantifies the maximal distance between the empirical distribution of the two samples, and establishes wether the



verifies the statistical hypothesis H0 (null
hypothesis) that they come from the same distribution. This test finds the maximum
distance among the two distributions of the samples and establishes, with tabulated values
depending on how big the sample is and the significance level α, if the distributions should
be considered distinct. The significance level α indicates the maximum probability that
is verified as a Type I error (H0 is rejected although it is true).

# hai usato la libreria scipy.
